
import { AwardProvider } from "@/context/award_context";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Darpan Magazine | Awards",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AwardProvider>
      {children}
    </AwardProvider>
  );
}
